Задание 1

In [7]:
import numpy as np
start = int(input())
stop = int(input())
n = int(input())
q = 2
b = 0
for i in range(n):
  print((start+b)*q)
  b+=1

0
10
3
0
2
4


Задача 2

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
b = a.reshape(a.shape[1],a.shape[0])
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    b[j][i] = a[i][j]
print(b)

[[1 4]
 [2 2]
 [2 6]]


Задание 3


In [19]:
a = np.array([[1, 1, 2], [2, 2, 2], [7, 8, 9], [13, 13, 13], [7, 4, 3], [1, 1, 1], [9, 10, 1], [2, 2, 2]], int)
b = np.array([[2, 2], [1, 1]], int)
for i in range(a.shape[0]):
  if (((b[0][0] in a[i][:]) or (b[0][1] in a[i][:]) or (b[1][0] in a[i][:])) and ((b[1][0] in a[i][:]) or (b[1][1] in a[i][:]) or (b[0][1] in a[i][:]))):
    print(a[i][:])


[1 1 2]
[2 2 2]
[1 1 1]
[ 9 10  1]
[2 2 2]


Задание 4
