# Вариант 1.

Кто делает:
1. Анохин Георгий Александрович
2. Георгиев Денис Дмитриевич 
3. Горячев Иван Сергеевич
4. Даниярбек уулу Нурбол

**Задача 1.**

**1-я входная строка** - год (опционально месяц и день) в формате ISO начала отсчёта.

**2-я входная строка** - год (опционально месяц и день) в формате ISO окончания отсчёта.

Создайте функцию, которая принимает на вход два введенных года и возвращает список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

- 2005 - год
- 02 - месяц
- 25 - день

In [ ]:
import numpy as np

#обработка времени 
class Date:
    __days = [31,28,31,30,31,30,31,31,30,31,30,31]
    year = 0
    month = 0
    day = 0
    def __init__(self, year, month, day):
        self.year = year
        self.month = month
        self.day = day

    def __eq__(self, date):
        return self.year == date.year and self.month == date.month and self.day == date.day

    def __ne__(self, date):
        return self.year != date.year or self.month != date.month or self.day != date.day

    def nextDate(self):
        if self.day < self.__days[self.month - 1]:
            self.day += 1
            return
        if self.month < 12:
            self.month += 1
            self.day = 1
            return 
        self.month = 1
        self.day = 1
        self.year += 1

    def getInfo(self):
        return str(self.year) + '-' + \
        (str(self.month) if self.month // 10 > 0 else '0' + str(self.month)) + '-' + \
        (str(self.day) if self.day // 10 > 0 else '0' + str(self.day))
    
#
def fun(d1, d2):
    spis = []
    while d1 != d2:
        spis.append(d1.getInfo())
        d1.nextDate()    

    return np.array(spis)

#
a1 = list(map(int, input().split('-')))
a2 = list(map(int, input().split('-')))

d1 = Date(a1[0], a1[1], a1[2])
d2 = Date(a2[0], a2[1], a2[2])

spis = fun(d1, d2)

print(spis)

**Задача 2.**

Используя numpy:

Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.

In [ ]:
import numpy as np

def fun(n, a1, d):
    mas = np.zeros((n, n), dtype=float)
    for i in range(n):
        mas[i][i] = a1 + d * i
    return mas

n = int(input())
a1 = float(input())
d = float(input())

print(fun(n, a1, d))

**Задача 3.**

Дан массив. Создайте функцию, которая принимает данный массив и проверяет наличие пропусков и возвращает их количество:
- если есть пропуски, то функция должна их заполнить теми значениями, которые пользователь вводит с клавиатуры.
- если нет пропусков, то функция возвращает 0.

*Встроенные функции заполнения пропусков использовать запрещено.*

In [ ]:
import numpy as np

def fun(mas):
    space = None
    spis, = np.where(mas == space, )
    count = len(spis)

    mas.flatten()

    for index in spis:
        mas[index] = int(input('input space: '))

    return mas, count

print(fun(np.array([1, None, 3, 4, None, 12, None])))

**Задача 4.**

Вам дан массив, содержащий категории некоторого объекта в виде строк.

Создайте функцию, которая принимает на вход массив, хранящий категории объектов и возвращает:
- закодированный список из чисел, где каждому числу соответсвует какая-то категория;
- число категорий;
- словарь кодирования;

**Например:**

Ввод:

`('red', 'green', 'red', 'blue')`

Вывод:
```(0, 1, 0, 2)
Количество категорий: 3
Словарь кодирования: 
{'red': 0, 'green': 1, 'blue': 2'}
```

*P.s. встроенными функциями кодирования пользоваться запрещено.*

In [ ]:
import numpy as np

def fun(slov):
    d = dict.fromkeys(list(slov))
    id = 0
    for i in d.keys():
        d[i] = id
        id += 1
    return id, d

print(fun(('red', 'blue', 'dark', 'red', 'blue', 'purple')))




# Вариант 2.

Кто делает:
1. Дорохов Матвей Дмитриевич 
2. Зайцев Егор Андреевич
3. Зверев Александр Александрович 
4. Зимина Александра Георгиевна

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая принимает 3 введеных числа и возвращает список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дан массив размерностью NxM.

Напишите функцию, которая нормализует все элементы матрицы.

**Немного теории.** *Нормализацией данных называется приведение их к некоторой общей шкале без потери информации о различии диапазонов.*

*Новые значения элементов расчитываются как:*

$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$

In [ ]:
# ваше решение

**Задача 3.**

Вам дан одномерный массив. Напишите функцию, которая принимает этот массив и возвращает:
1. Количество локальных максимумов для этого массива;
2. И сами эти максимумы.

*P.s. встроенными функциями пользоваться запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Реализуйте функцию умножения двух матриц, без использования встроенной функции.

In [ ]:
# ваше решение

# Вариант 3.

Кто делает:

1. Иванов Александр Андреевич 
2. Калентьев (Топилин) Константин Юрьевич
3. Мартюшев Владислав Алексеевич
4. Нечаев Никита Максимович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [ ]:
# ваше решение

**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [ ]:
# ваше решение

# Вариант 4.

Кто делает:
1. Нуромский Евгений Михайлович
2. Родин Андрей Дмитриевич
3. Рыженко Роман Владиславович
4. Юлов Егор Владимирович 

**Задача 1.**

Реализовать функцию, которая принимает матрицу 3x3 и возвращает обратную по отношеную к ней матрицу.

**Немного теории**. *Матрица $А^{-1}$ называется обратной матрицей по отношению к матрице $А$, если $А*А^{-1} = Е$, где $Е$ — единичная матрица n-го порядка. Обратная матрица может существовать только для квадратных матриц.*

P.s. использовать встроенные функции запрещено.

In [ ]:
# ваше решение

**Задача 2.**

Дан одномернный массив. Создайте функцию, которая принимает данные массив и возвращает массив, состоящий из элементов, целая часть от деления которых больше 3.

In [ ]:
# ваше решение

**Задача 3.**

Дана матрица 4х3 (содержащаяя координаты 4х векторов, столбцы это соотсветсвенно x,y,z) и вектор (x,y,z). Напишите функцию которая возвращает ближащий вектор из матрицы к заданому вектору (согласно расстоянию между векторами).

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор из ненулевых элементов. Вставьте между каждыми элементами по три 0.

In [ ]:
# ваше решение