# Вариант 3.

Кто делает:

1. Иванов Александр Андреевич 
2. Калентьев (Топилин) Константин Юрьевич
3. Мартюшев Владислав Алексеевич
4. Нечаев Никита Максимович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [ ]:
import numpy as np
start = float(input())
stop = float(input())
n = int(input())
d = (stop / start) ** (1 / (n - 1))
arr = np.fromiter((round(start * (d  ** i), 3)  for i in range(0,  n)), float)
arr

100
1
3


array([100.,  10.,   1.])

**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [ ]:
import numpy as np


def transpose(matrix: np.ndarray):
    new_matrix = np.zeros(matrix.shape[::-1])
    for i in range(matrix.shape[0]):
        new_matrix[:, i] = matrix[i, :]
    return new_matrix

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0.,  3.,  6.,  9.],
       [ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.]])

**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

In [ ]:
import numpy as np

a = np.random.random_integers(size=(8, 3), high=4, low=1);
b = np.random.random_integers(size=(2, 2), high=4, low=1);
print(a)
print(b)
for i in a:
    is_true = True
    for j in b:
        if not any([k in j for k in i]):
          is_true = False
          break
    if (is_true):
        print(*i)


[[3 4 2]
 [1 3 1]
 [4 3 4]
 [3 3 2]
 [2 3 4]
 [1 3 4]
 [2 4 4]
 [4 4 2]]
[[4 4]
 [4 4]]
3 4 2
4 3 4
2 3 4
1 3 4
2 4 4
4 4 2


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 4 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 4 + 1) instead
  after removing the cwd from sys.path.


**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [56]:
import numpy as np
a = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])


def vec_bin(a):
    return np.array([np.array(list(map(int, bin(i)[2:].rjust(8, "0")))) for i in a])

vec_bin(a)



array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])