# Вариант 3.

Кто делает:

1. Иванов Александр Андреевич 
2. Калентьев (Топилин) Константин Юрьевич
3. Мартюшев Владислав Алексеевич
4. Нечаев Никита Максимович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [1]:
import numpy as np
a = []
def f(start, stop, n):
  q = pow((stop / start), 1/(n-1))
  for i in range(1, n + 1):
    a.append(round(start * pow(q, i-1), 3))
    print(round(start * pow(q, i-1), 3))

f(int(input()), int(input()), int(input()))

2
8192
13
2.0
4.0
8.0
16.0
32.0
64.0
128.0
256.0
512.0
1024.0
2048.0
4096.0
8192.0


**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [2]:
def f(matr):
  a = np.array(matr, int)
  b = np.array([[0]*a.shape[0]]*a.shape[1])
  for i in range(a.shape[0]):
    for j in range(a.shape[1]):
      b[j][i] = a[i][j]
  print(b)
grid = [[1, 2, 3], [4, 5, 6]]
f(grid)

[[1 4]
 [2 5]
 [3 6]]


**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

In [4]:
def f(ma, mb):
  a = np.array(ma, int)
  b = np.array(mb, int)
  for i in range(a.shape[0]):
    if (((b[0][0] in a[i][:]) or (b[0][1] in a[i][:])) and ((b[1][0] in a[i][:]) or (b[1][1] in a[i][:]))):
      print(a[i][:])

grid1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]
grid2 = [[1, 2], [3, 4]]
f(grid1, grid2)

[1 2 3]


**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [6]:
def f(mas):
  a = np.array(mas, int)
  b = np.log2(a)
  maxi = int(np.ceil(np.max(b))) + 1
  c = np.array([[0]*maxi]*a.shape[0])
  for i in range(a.shape[0]):
    if (int(a[i]) != 0):
      if (int(a[i]) == 1):
        c[i][maxi - 1] = 1
      else:
        chisl = bin(int(a[i]))[2:]
        k = len(chisl)
        while(len(chisl)>0):
          c[i][maxi - k] = int(chisl[0])
          chisl = chisl[1:]
          k -=1
  print(c)
  

grid = [0, 1, 2, 3, 15, 16, 32, 64, 128]
f(grid)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log2
  This is separate from the ipykernel package so we can avoid doing imports until
